### ISSUE TITLE
Add User Update

### ISSUE THREAD

**Issue by CjMoore** [CjMoore/Weasley-wizarding-wheezes#82]
- User stories only specify the Admin can edit themselves.

**Comment by CjMoore** [comment]
Should the admin be able to update their password? Should we have a separate form where we re-authenticate them for updating a password? @s-espinosa @Carmer

**Comment by s-espinosa** [comment]
@CjMoore Based on story 17 it looks like an admin should be able to update their own data. I would include their password in that. I don't see anything indicating that you need to have them enter their existing password before updating (besides just being logged in).

That said, I think that having that password confirmation is a pretty common pattern. If you want to implement it, recommend that you think through how you want the UX to work. I wouldn't have a separate form, but maybe think about how to collect both a current password and a new password in the form and then only update if the current password was correct.

**Comment by Carmer** [comment]
@CjMoore I agree with @s-espinosa 

One other thing to consider would be requiring them to enter their current password in order to update it. That would be some fun interesting logic. I don't feel it is required since they have already authenticated to be logged in, but it would make it a stronger and more robust feature.
